Add "using" method in model queryset manager, which will be used to change database at runtime while querying.
tarsil/mongoz pull request #28
Opened 2024-04-24 13:20 UTC by harshalizode

The "using" method allows us to change the database at runtime while querying. If the user does not use the "using" method, it behaviour the same as before; however, I have included logic to change the database during runtime.

It is compatible with create, get, all, filter, with the exception of the update query, which needs to be modified in order to be used with the "using" method because it creates duplicate documents with the updated one.

We can use the "using" method as follows:

`User.objects.using("DB_NAME").all()`

2024-04-24 13:25 UTC, tarsil commented
@harshalizode this is great! Thank you so much for this but I need to ask you a couple of things. 

Can you update the docs to also have this using referenced there, please? Maybe in the queries.md?

Also, some tests to this would be great to have. Since it's mongo db, you can pass in the meta whatever you need.

2024-04-25 04:52 UTC, harshalizode commented
I have updated the doc and wrote test cases for it, and it passed.

2024-04-25 08:51 UTC, tarsil commented
@harshalizode the linting is failing.

In your local machine run:

```shell
scripts/lint
```

This should fix the problems

2024-04-25 10:37 UTC, harshalizode commented
Which linter is used in MongoZ?

2024-04-25 10:41 UTC, tarsil commented
@harshalizode mongoz repo has everything you need. Here https://mongoz.tarsild.io/contributing/ contains what you need to do to run it locally.

Although there is a bug there I need to fix. its not `scripts/format` anymore but `scripts/lint`.

When you install the requirements and run those commands and pass, it should pass in the CI as well since it uses the same.

2024-04-26 18:47 UTC, tarsil commented
@harshalizode if you can run the `scripts/install` + `scripts/lint` this errors should be easily addressed and you can push them.

It would be great to have this great feature in Mongoz.

2024-04-29 08:45 UTC, harshalizode commented
I have resolved the Linter issues.

2024-04-29 08:51 UTC, tarsil commented
@harshalizode still complains? Did you run the scripts/lint? 

Maybe you can also install the pre-commits and run it

2024-04-29 09:51 UTC, harshalizode commented
I have resolved all the issues.
![Uploading success_lint.png…]()

2024-04-29 09:54 UTC, tarsil commented
> I have resolved all the issues. ![success_lint](https://private-user-images.githubusercontent.com/66934194/326396458-eff3e8a9-b611-4266-966a-6d1e1093b363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODQ2MjMsIm5iZiI6MTcxNDM4NDMyMywicGF0aCI6Ii82NjkzNDE5NC8zMjYzOTY0NTgtZWZmM2U4YTktYjYxMS00MjY2LTk2NmEtNmQxZTEwOTNiMzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA5NTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxN2U0YjE2MTVjNzIwYjg1NzRhM2M2ZDUzZDI5YWMwMWQwZmY3OGI4MmQxY2ZkMWE5MDgyNmUyM2QyNzQ3NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tbkTNhTWJUlKSCZXNii5eFPfZ_aKyg4H8wdr_xQnWW4)

I can see that but once you resolve them you need to still do a git add and git push for the CI to run.

2024-04-29 09:58 UTC, tarsil requested changes

2024-04-29 09:58 UTC, tarsil commented on mongoz/core/db/documents/document.py
> +    async def create(self: "Document", collection: AsyncIOMotorCollection = None) -> "Document":  # type: ignore
Maybe here it is better to 

```python
 collection: Union[AsyncIOMotorCollection, None] = None
```

2024-04-29 09:58 UTC, tarsil commented
Overall the PR looks good besides the minor changes requested 👍🏼

2024-04-29 12:52 UTC, harshalizode commented on mongoz/core/db/documents/document.py
> +    async def create(self: "Document", collection: AsyncIOMotorCollection = None) -> "Document":  # type: ignore
Done.

2024-04-29 13:22 UTC, tarsil commented
@harshalizode the linting is still a problem. 

This is what I would do. 

1. Install the pre-commit
2. git init (no worries just to start the pre commit)
3. scripts/lint
4. git add
5. git push

2024-05-02 10:29 UTC, harshalizode commented
Yes, after following the steps, I had two issues, which I resolved.

2024-05-02 11:04 UTC, merged

2024-05-02 12:05 UTC, tarsil commented
@harshalizode congratulation! Your PR made it into the new release 0.8.0 :)

2024-05-02 12:35 UTC, harshalizode commented
Thanks for all your assistance :)

2024-05-02 12:36 UTC, tarsil commented
> Thanks for all your assistance :)

Anytime :). How is Esmerald and Mongoz working for you?

2024-05-02 12:58 UTC, harshalizode commented
Both Esmerald and Mongoz are nice, but when utilizing Esmerald with Mongoz, there are certain difficulties, such as:
1) Extending a Document to override the QueryManager.
2) MOGOZ.Date field has a parsing issue.
We have identified a few problems and need to find a solution.

2024-05-02 13:32 UTC, tarsil commented
@harshalizode ok good to know. Let's fix those then. Esmerald has nothing to do with that apparently. Do you still have the extending problem? 

Can you provide me examples of all the issues you are currently facing? 

This way we can address them

2024-05-03 04:43 UTC, harshalizode commented
Yes, there is still an issue with overriding the QueryManager.

I use the Abstract document as the BaseDocument by inheriting the mongoz.Document.
I have replaced the Quermanager with the CustomManager.
```
class BaseDocument(mongoz.Document):
    """
    The base document for all documents using the `registry` registry.
    """
    objects: ClassVar[CustomManger] = CustomManger()

    class Meta:
        """
            It contains the Meta information related the database for \
                each model level.
        """
        abstract = True
        registry = settings.client
        database = settings.db
```

Now, I'm trying to inherit the BaseDocument into my view as

```
class Employee(BaseDocument):
    month_period: int = mongoz.Integer(null=True)
    full_name: str = mongoz.String()
    employee_code: str = mongoz.String()
    date_of_joining: datetime.datetime = mongoz.DateTime(null=True)
    e_mail: str = mongoz.String(null=True)
    mobile_no: str = mongoz.String(null=True)
```
Whenever I try to query in MongoDB using the manager as `Employee.objects.all()`
`Employee.objects` returns me the Manager (Default Manager) and not the CustomManager.

That's why I'm overriding the manager at the model level.
```
class Employee(BaseDocument):
    month_period: int = mongoz.Integer(null=True)
    full_name: str = mongoz.String()
    employee_code: str = mongoz.String()
    date_of_joining: datetime.datetime = mongoz.DateTime(null=True)
    e_mail: str = mongoz.String(null=True)
    mobile_no: str = mongoz.String(null=True)

    objects: ClassVar[CustomManger] = CustomManger()
```

Thanks.